<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Translation engine
    |--------------------------------------------------------------------------
    | The browser engine uses the device's Web Speech API (free, on-device STT
    | + TTS). The text translation step is proxied through a provider below.
    | Premium plans may switch the provider to a paid cloud engine.
    */

    'default_engine' => env('TRANSLATOR_ENGINE', 'browser'),

    'provider' => env('TRANSLATE_PROVIDER', 'mymemory'), // mymemory | libretranslate

    'mymemory' => [
        'endpoint' => 'https://api.mymemory.translated.net/get',
        // optional e-mail raises the free daily quota
        'email' => env('MYMEMORY_EMAIL'),
    ],

    'libretranslate' => [
        'endpoint' => env('LIBRETRANSLATE_URL', 'https://libretranslate.com'),
        'api_key' => env('LIBRETRANSLATE_KEY'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Affiliate program (multi-level, ganacon style)
    |--------------------------------------------------------------------------
    | Commission percentage earned on each paid subscription generated by the
    | referral network, by depth level.
    */

    'affiliate' => [
        'levels' => [
            1 => env('AFFILIATE_L1', 30), // direct referral
            2 => env('AFFILIATE_L2', 10), // referral of a referral
            3 => env('AFFILIATE_L3', 5),  // third level
        ],
        'cookie_days' => 30,
        'min_payout_cents' => 2000, // €20 minimum withdrawal
    ],

    /*
    |--------------------------------------------------------------------------
    | UI interface locales
    |--------------------------------------------------------------------------
    | Locales the application chrome (menus, buttons, marketing) is translated
    | into. Missing keys fall back to 'fallback_locale'. New locales can be
    | auto-populated with: php artisan translations:sync {locale}
    */

    'fallback_locale' => 'en',

    'ui_locales' => ['es', 'en', 'fr', 'de', 'it', 'pt', 'ca', 'eu', 'gl'],

    /*
    |--------------------------------------------------------------------------
    | Supported audio languages
    |--------------------------------------------------------------------------
    | Source/target languages for live audio translation. `speech` is the
    | BCP-47 locale fed to the Web Speech API; `ui` marks languages also offered
    | as an interface language. Seeded into the `languages` table.
    */

    'languages' => [
        ['code' => 'af', 'name' => 'Afrikaans', 'native' => 'Afrikaans', 'flag' => '🇿🇦', 'speech' => 'af-ZA'],
        ['code' => 'sq', 'name' => 'Albanian', 'native' => 'Shqip', 'flag' => '🇦🇱', 'speech' => 'sq-AL'],
        ['code' => 'am', 'name' => 'Amharic', 'native' => 'አማርኛ', 'flag' => '🇪🇹', 'speech' => 'am-ET'],
        ['code' => 'ar', 'name' => 'Arabic', 'native' => 'العربية', 'flag' => '🇸🇦', 'speech' => 'ar-SA'],
        ['code' => 'hy', 'name' => 'Armenian', 'native' => 'Հայերեն', 'flag' => '🇦🇲', 'speech' => 'hy-AM'],
        ['code' => 'az', 'name' => 'Azerbaijani', 'native' => 'Azərbaycan', 'flag' => '🇦🇿', 'speech' => 'az-AZ'],
        ['code' => 'eu', 'name' => 'Basque', 'native' => 'Euskara', 'flag' => '🟢', 'speech' => 'eu-ES', 'ui' => true],
        ['code' => 'be', 'name' => 'Belarusian', 'native' => 'Беларуская', 'flag' => '🇧🇾', 'speech' => 'be-BY'],
        ['code' => 'bn', 'name' => 'Bengali', 'native' => 'বাংলা', 'flag' => '🇧🇩', 'speech' => 'bn-BD'],
        ['code' => 'bs', 'name' => 'Bosnian', 'native' => 'Bosanski', 'flag' => '🇧🇦', 'speech' => 'bs-BA'],
        ['code' => 'bg', 'name' => 'Bulgarian', 'native' => 'Български', 'flag' => '🇧🇬', 'speech' => 'bg-BG'],
        ['code' => 'ca', 'name' => 'Catalan', 'native' => 'Català', 'flag' => '🟡', 'speech' => 'ca-ES', 'ui' => true],
        ['code' => 'zh', 'name' => 'Chinese (Mandarin)', 'native' => '中文', 'flag' => '🇨🇳', 'speech' => 'zh-CN'],
        ['code' => 'zh-TW', 'name' => 'Chinese (Traditional)', 'native' => '繁體中文', 'flag' => '🇹🇼', 'speech' => 'zh-TW'],
        ['code' => 'hr', 'name' => 'Croatian', 'native' => 'Hrvatski', 'flag' => '🇭🇷', 'speech' => 'hr-HR'],
        ['code' => 'cs', 'name' => 'Czech', 'native' => 'Čeština', 'flag' => '🇨🇿', 'speech' => 'cs-CZ'],
        ['code' => 'da', 'name' => 'Danish', 'native' => 'Dansk', 'flag' => '🇩🇰', 'speech' => 'da-DK'],
        ['code' => 'nl', 'name' => 'Dutch', 'native' => 'Nederlands', 'flag' => '🇳🇱', 'speech' => 'nl-NL'],
        ['code' => 'en', 'name' => 'English', 'native' => 'English', 'flag' => '🇬🇧', 'speech' => 'en-US', 'ui' => true],
        ['code' => 'et', 'name' => 'Estonian', 'native' => 'Eesti', 'flag' => '🇪🇪', 'speech' => 'et-EE'],
        ['code' => 'fil', 'name' => 'Filipino', 'native' => 'Filipino', 'flag' => '🇵🇭', 'speech' => 'fil-PH'],
        ['code' => 'fi', 'name' => 'Finnish', 'native' => 'Suomi', 'flag' => '🇫🇮', 'speech' => 'fi-FI'],
        ['code' => 'fr', 'name' => 'French', 'native' => 'Français', 'flag' => '🇫🇷', 'speech' => 'fr-FR', 'ui' => true],
        ['code' => 'gl', 'name' => 'Galician', 'native' => 'Galego', 'flag' => '🔵', 'speech' => 'gl-ES', 'ui' => true],
        ['code' => 'ka', 'name' => 'Georgian', 'native' => 'ქართული', 'flag' => '🇬🇪', 'speech' => 'ka-GE'],
        ['code' => 'de', 'name' => 'German', 'native' => 'Deutsch', 'flag' => '🇩🇪', 'speech' => 'de-DE', 'ui' => true],
        ['code' => 'el', 'name' => 'Greek', 'native' => 'Ελληνικά', 'flag' => '🇬🇷', 'speech' => 'el-GR'],
        ['code' => 'gu', 'name' => 'Gujarati', 'native' => 'ગુજરાતી', 'flag' => '🇮🇳', 'speech' => 'gu-IN'],
        ['code' => 'he', 'name' => 'Hebrew', 'native' => 'עברית', 'flag' => '🇮🇱', 'speech' => 'he-IL'],
        ['code' => 'hi', 'name' => 'Hindi', 'native' => 'हिन्दी', 'flag' => '🇮🇳', 'speech' => 'hi-IN'],
        ['code' => 'hu', 'name' => 'Hungarian', 'native' => 'Magyar', 'flag' => '🇭🇺', 'speech' => 'hu-HU'],
        ['code' => 'is', 'name' => 'Icelandic', 'native' => 'Íslenska', 'flag' => '🇮🇸', 'speech' => 'is-IS'],
        ['code' => 'id', 'name' => 'Indonesian', 'native' => 'Indonesia', 'flag' => '🇮🇩', 'speech' => 'id-ID'],
        ['code' => 'ga', 'name' => 'Irish', 'native' => 'Gaeilge', 'flag' => '🇮🇪', 'speech' => 'ga-IE'],
        ['code' => 'it', 'name' => 'Italian', 'native' => 'Italiano', 'flag' => '🇮🇹', 'speech' => 'it-IT', 'ui' => true],
        ['code' => 'ja', 'name' => 'Japanese', 'native' => '日本語', 'flag' => '🇯🇵', 'speech' => 'ja-JP'],
        ['code' => 'kn', 'name' => 'Kannada', 'native' => 'ಕನ್ನಡ', 'flag' => '🇮🇳', 'speech' => 'kn-IN'],
        ['code' => 'kk', 'name' => 'Kazakh', 'native' => 'Қазақ', 'flag' => '🇰🇿', 'speech' => 'kk-KZ'],
        ['code' => 'km', 'name' => 'Khmer', 'native' => 'ខ្មែរ', 'flag' => '🇰🇭', 'speech' => 'km-KH'],
        ['code' => 'ko', 'name' => 'Korean', 'native' => '한국어', 'flag' => '🇰🇷', 'speech' => 'ko-KR'],
        ['code' => 'lo', 'name' => 'Lao', 'native' => 'ລາວ', 'flag' => '🇱🇦', 'speech' => 'lo-LA'],
        ['code' => 'lv', 'name' => 'Latvian', 'native' => 'Latviešu', 'flag' => '🇱🇻', 'speech' => 'lv-LV'],
        ['code' => 'lt', 'name' => 'Lithuanian', 'native' => 'Lietuvių', 'flag' => '🇱🇹', 'speech' => 'lt-LT'],
        ['code' => 'mk', 'name' => 'Macedonian', 'native' => 'Македонски', 'flag' => '🇲🇰', 'speech' => 'mk-MK'],
        ['code' => 'ms', 'name' => 'Malay', 'native' => 'Melayu', 'flag' => '🇲🇾', 'speech' => 'ms-MY'],
        ['code' => 'ml', 'name' => 'Malayalam', 'native' => 'മലയാളം', 'flag' => '🇮🇳', 'speech' => 'ml-IN'],
        ['code' => 'mt', 'name' => 'Maltese', 'native' => 'Malti', 'flag' => '🇲🇹', 'speech' => 'mt-MT'],
        ['code' => 'mr', 'name' => 'Marathi', 'native' => 'मराठी', 'flag' => '🇮🇳', 'speech' => 'mr-IN'],
        ['code' => 'mn', 'name' => 'Mongolian', 'native' => 'Монгол', 'flag' => '🇲🇳', 'speech' => 'mn-MN'],
        ['code' => 'ne', 'name' => 'Nepali', 'native' => 'नेपाली', 'flag' => '🇳🇵', 'speech' => 'ne-NP'],
        ['code' => 'no', 'name' => 'Norwegian', 'native' => 'Norsk', 'flag' => '🇳🇴', 'speech' => 'nb-NO'],
        ['code' => 'fa', 'name' => 'Persian', 'native' => 'فارسی', 'flag' => '🇮🇷', 'speech' => 'fa-IR'],
        ['code' => 'pl', 'name' => 'Polish', 'native' => 'Polski', 'flag' => '🇵🇱', 'speech' => 'pl-PL'],
        ['code' => 'pt', 'name' => 'Portuguese', 'native' => 'Português', 'flag' => '🇵🇹', 'speech' => 'pt-PT', 'ui' => true],
        ['code' => 'pt-BR', 'name' => 'Portuguese (Brazil)', 'native' => 'Português (BR)', 'flag' => '🇧🇷', 'speech' => 'pt-BR'],
        ['code' => 'pa', 'name' => 'Punjabi', 'native' => 'ਪੰਜਾਬੀ', 'flag' => '🇮🇳', 'speech' => 'pa-IN'],
        ['code' => 'ro', 'name' => 'Romanian', 'native' => 'Română', 'flag' => '🇷🇴', 'speech' => 'ro-RO'],
        ['code' => 'ru', 'name' => 'Russian', 'native' => 'Русский', 'flag' => '🇷🇺', 'speech' => 'ru-RU'],
        ['code' => 'sr', 'name' => 'Serbian', 'native' => 'Српски', 'flag' => '🇷🇸', 'speech' => 'sr-RS'],
        ['code' => 'si', 'name' => 'Sinhala', 'native' => 'සිංහල', 'flag' => '🇱🇰', 'speech' => 'si-LK'],
        ['code' => 'sk', 'name' => 'Slovak', 'native' => 'Slovenčina', 'flag' => '🇸🇰', 'speech' => 'sk-SK'],
        ['code' => 'sl', 'name' => 'Slovenian', 'native' => 'Slovenščina', 'flag' => '🇸🇮', 'speech' => 'sl-SI'],
        ['code' => 'es', 'name' => 'Spanish', 'native' => 'Español', 'flag' => '🇪🇸', 'speech' => 'es-ES', 'ui' => true],
        ['code' => 'sw', 'name' => 'Swahili', 'native' => 'Kiswahili', 'flag' => '🇰🇪', 'speech' => 'sw-KE'],
        ['code' => 'sv', 'name' => 'Swedish', 'native' => 'Svenska', 'flag' => '🇸🇪', 'speech' => 'sv-SE'],
        ['code' => 'ta', 'name' => 'Tamil', 'native' => 'தமிழ்', 'flag' => '🇮🇳', 'speech' => 'ta-IN'],
        ['code' => 'te', 'name' => 'Telugu', 'native' => 'తెలుగు', 'flag' => '🇮🇳', 'speech' => 'te-IN'],
        ['code' => 'th', 'name' => 'Thai', 'native' => 'ไทย', 'flag' => '🇹🇭', 'speech' => 'th-TH'],
        ['code' => 'tr', 'name' => 'Turkish', 'native' => 'Türkçe', 'flag' => '🇹🇷', 'speech' => 'tr-TR'],
        ['code' => 'uk', 'name' => 'Ukrainian', 'native' => 'Українська', 'flag' => '🇺🇦', 'speech' => 'uk-UA'],
        ['code' => 'ur', 'name' => 'Urdu', 'native' => 'اردو', 'flag' => '🇵🇰', 'speech' => 'ur-PK'],
        ['code' => 'uz', 'name' => 'Uzbek', 'native' => 'Oʻzbek', 'flag' => '🇺🇿', 'speech' => 'uz-UZ'],
        ['code' => 'vi', 'name' => 'Vietnamese', 'native' => 'Tiếng Việt', 'flag' => '🇻🇳', 'speech' => 'vi-VN'],
        ['code' => 'cy', 'name' => 'Welsh', 'native' => 'Cymraeg', 'flag' => '🏴', 'speech' => 'cy-GB'],
        ['code' => 'zu', 'name' => 'Zulu', 'native' => 'isiZulu', 'flag' => '🇿🇦', 'speech' => 'zu-ZA'],
    ],
];
